### ISSUE TITLE
TokenRemover stops running

### ISSUE THREAD

**Issue by tonoitp** [MennovH/HomeAssistant#3]
The plugin (1.0.2) starts (and works) but stops after a few seconds.
Should it not stay in the 'started' state?

**Comment by MennovH** [comment]
Hi @tonoitp ,

Good to hear it works within your HA instance.

Momentarily I have only created it the way it is. So it will only run once. An automation could help restart it at times you define.
I have thought about user-defined reoccurrence within the add-on, but haven't had the time to think it through and implement it yet. For instance, I don't want it to continuously look for "expired" tokens, because it would generate more overhead - depending on the defined number of retention days. Also it preferrably should run when no users are active, because it may restart the core.

If I would create something like this, what would you prefer regarding the reoccurence?

**Comment by tonoitp** [comment]
Ah, great.  I suspected something like that, but the appearance of a restart button after start made me think otherwise.

Regarding the  reoccurence, first thing that sprang to mind is 'half-life' (so if the lifetime is a week, it would run every 3,5 days). Then again daily sounds justified and simpler too.

**Comment by MennovH** [comment]
Check, that makes sense. For myself, I have an automation in place which runs it every night.

Because of the number of retention days and the possibility of keeping tokens within the number of activation days, there are some variables regarding the lifetime. Maybe I can make the add-on - when enabled - create an automation by itself, so it would still run only once, but that it is restarted automatically (based on user input), without having the add-on run constantly (this would also remove the need of a time loop in the add-on).

Would this option where you can define on which days and which time the add-on should run, suffice?

**Comment by tonoitp** [comment]
It would. No need to make it more complicated than that. After all we're not talking bank-accounts here ;)

**Comment by MennovH** [comment]
I have tried to auto create an automation in the test add-on, but it appears it needs a reboot in order for it to activate it. Which I don't want.

Therefore, I have implemented a while loop in the test add-on called TEST_TokenRemover*, where you can specify the time (AM/PM/Both) and on which days (Monday, Tuesday, et cetera) it should run. If no recurring day is specified, it will run only once. I have tested it as far as I could, and no problems here. But I can only confirm for myself in regards to the time zone I'm in.

Could you please try the test add-on for a while? If all is well, I will update the original version, and remove the test version.

*I practically cloned the original and made changes to it, so the documentation hasn't been updated yet. I do think the handling is pretty self-explanatory.

**Comment by MennovH** [comment]
Updated original with the test configuration, after having it tested for a few months.
